# Project Information
site_name: LLVM Wiki
site_description: The LLVM Wiki provides wiki documentation on reusable compilation techniques
site_author: LLVM Wiki Team
site_url: https://llvm.wiki
strict: false

# Repository
repo_name: 'llvm-wiki/llvm-wiki'
repo_url: 'https://github.com/llvm-wiki/llvm-wiki'
edit_uri: 'https://llvm.wiki/edit-landing/?ref='

# Copyright
copyright: 'Copyright &copy; 2016 - 2022 LLVM Wiki team'

plugins:
  - search
  - i18n:
      languages:
        en: "English"
        zh: "简体中文"
      default_language: 'en'
      no_translation:
        en: "This page isn't translated to English."
        zh: "这个页面还没有被翻译为简体中文"
      translate_nav:
        en:
          section title: "Section"
          subsection: "Subsection"
          page title: "Page with title translated"
        zh:
          section title: "节"
          subsection: "小节"
          page title: "标题被翻译过的页"
      add_lang_links: False


# Contents
nav:
  - LLVM Wiki: index.md
  - LLVM Wiki: index.zh.md

# Theme
theme:
  name: material
  language: 'en'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
  palette:
    primary: white

extra:
  # Default mkdocs-material alternate links for untranslated pages
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector
  alternate:
    - name: English
      link: ""
      lang: en

    - name: 简体中文
      link: index.zh/
      lang: zh
